name: roots-template
recipe: wordpress
config:
  webroot: site/web
  php: '8.3'
  via: nginx
  database: mariadb:10.6
  xdebug: false

services:
  appserver:
    build_as_root:
      - apt-get update && apt-get install -y git unzip
    overrides:
      environment:
        COMPOSER_ALLOW_SUPERUSER: 1

  database:
    type: mariadb:10.6
    creds:
      user: wordpress
      password: wordpress
      database: wordpress

  node:
    type: node:22
    ssl: false

tooling:
  composer:
    service: appserver
    cmd: composer
  wp:
    service: appserver
    cmd: wp --allow-root --path=/app/site/web/wp
  npm:
    service: node
    cmd: npm

proxy:
  appserver_nginx:
    - roots-template.lndo.site
    - 100.74.223.57
