# Created by trellis-cli v1.17.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  roots-template:
    site_hosts:
    - canonical: roots-template.lndo.site
      redirects: []
    local_path: ../site
    branch: master
    repo: git@github.com:example/example.com.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
